#!/bin/bash

clear
while true; do
echo "Ingrese 1: Para guardar uso de memoria, CPU, y disco en un log"
echo "Ingrese 2: Liberar espacio en la memoria"
echo "Ingrese 3: Hacer una copia de seguridad comprimida del directorio"
echo "Ingrese 4: Para salir"
read num

if [ "$num" -eq 1 ]; then
	us=$(free| grep Mem|awk '{print $3/$2 * 100.0}')
	cpu=$(top -bn1 | grep "Cpu(s)"|awk '{print $2 + $4}')
	disk=$(df -h / | grep '/'|awk '{print $5}')

	echo "Uso actual del CPU: $cpu%" > log
	echo "Uso actual de memoria: $us%" >> log
	echo "Uso actual del disco: $disk" >> log
	cat log
	echo "Datos guardados correctamente"

elif [ "$num" -eq 2 ]; then
	sudo rm -rf /tmp/*
	sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'
	rm -rf ~/.cache/chromium/*
	echo "Memoria liberada correctamente"

elif [ "$num" -eq 3 ]; then
	tar -czf /home/marti/TrabajoFinal.tar.gz /home/marti/TrabajoFinal
	echo "Directorio comprimido y copiado correctamente"

elif [ "$num" -eq 4 ]; then
	exit

else
	echo "Opcion incorrecta"
fi
done
